CREATE TABLE [dbo].[CLIENTS]
(
  [ID]    INT           NOT NULL  IDENTITY(1,1),
  [NAME]  NVARCHAR(50)  NOT NULL,
  [CPF]   NVARCHAR(11)  NOT NULL,
  CONSTRAINT PK_CLIENTS       PRIMARY KEY (ID),
  CONSTRAINT UI_CPF_CLIENTS   UNIQUE (CPF),
  CONSTRAINT CK_CPF           CHECK(LEN(CPF) = 11)
);
GO;
