CREATE TABLE [dbo].[SESSIONS]
(
  [ID]        INT             NOT NULL  IDENTITY(1,1),
  [CLIENTID]  INT             NOT NULL,
  [DATE]      DATETIMEOFFSET  NOT NULL,
  CONSTRAINT PK_SESSIONS         PRIMARY KEY (ID),
  CONSTRAINT FK_CLIENT_SESSIONS  FOREIGN KEY (CLIENTID) REFERENCES CLIENTS(ID)
);
GO;
